language: python

matrix:
  include:
  # Linux
    # Unit test
    - env: GOAL=unittest
      os: linux
      dist: trusty
      python: 2.7
      before_install:
        - pip --quiet install virtualenv
      script:
        - make test
  # Mac OS X
    # Unit test
    #- env: GOAL=unitttest
    #  os: osx
    #  language: generic
    #  osx_image: xcode7.3
    #  before_install:
    #    - brew update
    #    - which python || brew install python
    #    - pip install virtualenv
    #    - pip --quiet install virtualenv
    #  script:
    #    - make test

branches:
  only:
    - master

notifications:
  email: false
